#!/usr/bin/env python3
"""Interactive script to set up .env configuration."""

import os
from pathlib import Path

def main():
    print("=" * 70)
    print("ARIVU BACKEND CONFIGURATION SETUP")
    print("=" * 70)
    print()
    
    env_file = Path(".env")
    
    if env_file.exists():
        print("⚠️  A .env file already exists!")
        response = input("Do you want to overwrite it? (y/N): ").strip().lower()
        if response != 'y':
            print("Cancelled. Existing .env file preserved.")
            return
        print()
    
    print("This script will help you create a .env file with your configuration.")
    print()
    
    # Ask for OpenAI API key
    print("1. OpenAI API Key (optional, needed for GPT models)")
    print("   Get your API key from: https://platform.openai.com/api-keys")
    openai_key = input("   Enter your OpenAI API key (or press Enter to skip): ").strip()
    print()
    
    # Ask for backend preferences
    print("2. Choose your default LLM backend:")
    print("   a) Ollama (local, free, private)")
    print("   b) OpenAI (cloud, requires API key)")
    llm_choice = input("   Choice (a/b) [default: a]: ").strip().lower()
    llm_backend = "openai" if llm_choice == "b" else "ollama"
    print()
    
    print("3. Choose your default embedding backend:")
    print("   a) Local (HuggingFace, free, runs on your machine)")
    print("   b) OpenAI (cloud, requires API key)")
    emb_choice = input("   Choice (a/b) [default: a]: ").strip().lower()
    emb_backend = "openai" if emb_choice == "b" else "local"
    print()
    
    # Ollama configuration
    ollama_url = "http://localhost:11434"
    if llm_backend == "ollama" or emb_backend == "local":
        print("4. Ollama configuration:")
        custom_url = input(f"   Ollama URL [default: {ollama_url}]: ").strip()
        if custom_url:
            ollama_url = custom_url
        print()
    
    # Write .env file
    env_content = f"""# Arivu Backend Configuration
# Generated by setup_env.py

# OpenAI Configuration
ARIVU_OPENAI_API_KEY={openai_key}

# Backend Selection
ARIVU_LLM_BACKEND={llm_backend}
ARIVU_EMBEDDING_BACKEND={emb_backend}

# Ollama Configuration
ARIVU_OLLAMA_BASE_URL={ollama_url}
ARIVU_OLLAMA_MODEL=llama3

# OpenAI Models
ARIVU_OPENAI_CHAT_MODEL=gpt-4o-mini
ARIVU_OPENAI_EMBEDDING_MODEL=text-embedding-3-small

# Local Embedding Model
ARIVU_LOCAL_EMBEDDING_MODEL=all-MiniLM-L6-v2

# Database
ARIVU_DATABASE_URL=sqlite+aiosqlite:///data/arivu.db

# Data Directory
ARIVU_DATA_DIR=data

# RAG Configuration
ARIVU_DEFAULT_CHUNK_SIZE=1000
ARIVU_DEFAULT_CHUNK_OVERLAP=200
ARIVU_DEFAULT_TOP_K=5

# Debug Mode
ARIVU_DEBUG=false
"""
    
    env_file.write_text(env_content)
    
    print("=" * 70)
    print("✅ Configuration saved to .env")
    print("=" * 70)
    print()
    
    # Summary
    print("Summary:")
    print(f"  LLM Backend: {llm_backend}")
    print(f"  Embedding Backend: {emb_backend}")
    if openai_key:
        print(f"  OpenAI API Key: {openai_key[:8]}...{openai_key[-4:]}")
    else:
        print(f"  OpenAI API Key: Not configured")
    print(f"  Ollama URL: {ollama_url}")
    print()
    
    # Warnings
    if (llm_backend == "openai" or emb_backend == "openai") and not openai_key:
        print("⚠️  WARNING: You selected OpenAI backend but didn't provide an API key!")
        print("   You can add it later by editing the .env file.")
        print()
    
    if llm_backend == "ollama" or emb_backend == "local":
        print("ℹ️  Make sure Ollama is running:")
        print("   curl http://localhost:11434/api/tags")
        print()
    
    print("Next steps:")
    print("  1. Restart the backend server if it's running")
    print("  2. Run: python check_config.py   (to verify configuration)")
    print()

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\nCancelled by user.")
    except Exception as e:
        print(f"\n❌ Error: {e}")
        import traceback
        traceback.print_exc()
