
import pytest
from pathlib import Path
from unittest.mock import MagicMock, patch
import numpy as np
from sqlalchemy.ext.asyncio import AsyncSession
from app.db.models import Chunk, Document, Project
from app.rag.ingestion import ingest_document

# Mock embedding backend that returns consistent shapes
class MockEmbeddingBackend:
    def embed_texts(self, texts):
        return [np.random.rand(384).tolist() for _ in texts]

# Mock LLM backend
class MockLLMBackend:
    def generate(self, system, user):
        return "Summary content generated by LLM"

@pytest.mark.asyncio
async def test_raptor_ingestion_flow(db: AsyncSession, tmp_path: Path):
    # Setup project
    project = Project(name="Raptor Test")
    db.add(project)
    await db.commit()
    await db.refresh(project)
    
    # Create a large dummy file (enough to trigger RAPTOR > 10 chunks)
    # Chunk size default is 1000 chars. 
    # We need > 10 chunks, so > 10,000 chars.
    large_text = " ".join([f"This is sentence {i} of a large document." for i in range(2000)])
    doc_file = tmp_path / "large_doc.txt"
    doc_file.write_text(large_text)
    
    document = Document(
        project_id=project.id,
        filename="large_doc.txt",
        filetype="txt"
    )
    db.add(document)
    await db.commit()
    await db.refresh(document)
    
    # Mock backends
    with patch("app.rag.ingestion.get_embedding_backend", return_value=MockEmbeddingBackend()), \
         patch("app.rag.raptor.get_llm_backend", return_value=MockLLMBackend()), \
         patch("app.rag.ingestion.add_embeddings") as mock_add_embeddings:
             
        # Run ingestion
        # We need to ensure chunking produces > 10 chunks.
        # large_text length is approx 2000 * 30 = 60000 chars.
        # 60000 / 1000 = 60 chunks. Should trigger RAPTOR.
        
        num_chunks = await ingest_document(
            db,
            project_id=project.id,
            doc_id=document.id,
            file_path=doc_file,
            filetype="txt",
            filename="large_doc.txt"
        )
        
        # Verify
        assert num_chunks > 60 
        
        # Check DB for summary chunks (level > 0)
        # We need to query the DB directly
        result = await db.execute(
            Chunk.__table__.select().where(Chunk.document_id == document.id)
        )
        chunks = result.fetchall()
        
        # Check if any chunk has metadata with level > 0
        summary_chunks = []
        for c in chunks:
            # c is a Row, column access by name or index
            # accessing metadata_json kwarg
            # SQLAlchemy 2.0 Row access
            meta = c.metadata_json
            if meta and meta.get("level", 0) > 0:
                summary_chunks.append(c)
        
        print(f"Total chunks: {len(chunks)}")
        print(f"Summary chunks: {len(summary_chunks)}")
        
        assert len(summary_chunks) > 0, "No summary chunks created by RAPTOR"
        
        # Verify vector store addition was called with correct count
        assert mock_add_embeddings.called
        call_args = mock_add_embeddings.call_args
        # ids argument is index 1 or kwarg 'ids'
        added_ids = call_args.kwargs.get('ids') or call_args.args[1]
        assert len(added_ids) == len(chunks)
